project:
  type: website

website:
  title: "cap5765 notes"
  background: "#41522a"
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/isabelizimm
      - icon: twitter
        href: https://twitter.com/isabelizimm
format:
  html:
    theme: [cosmo, styles.scss]
