project:
  type: website

website:
  title: "CAP5765"
  background: "#41522a"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/isabelizimm
      - icon: twitter
        href: https://twitter.com/isabelizimm
format:
  html:
    theme: cosmo
    css: styles.css



